apiVersion: v1
kind: Service
metadata:
  name: greeter-svc
  namespace: exercises
  labels:
    app: greeter
spec:
  type: ClusterIP
  selector:
    app: greeter
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      name: http
