apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Traditional deployment (comment out when using serverless)
  # - deployment.yaml
  # - service.yaml
  # - gateway.yaml
  # - virtualservice.yaml
  # Serverless deployment (comment out when using traditional)
  - knative-service.yaml
  # Always needed
  - postgres-statefulset.yaml
images:
  - name: PROJECT/IMAGE
    newName: typescriptlover/ping_pong
    newTag: cad8d36074b29e42d60bcbbe9682608369d6b27b
