apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - postgres-statefulset.yaml
  - httproute.yaml
images:
  - name: PROJECT/IMAGE
    newName: typescriptlover/ping_pong
    newTag: placeholder
