apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- postgres-statefulset.yaml
- gateway.yaml
- virtualservice.yaml
images:
- name: PROJECT/IMAGE
  newName: typescriptlover/ping_pong
  newTag: cad8d36074b29e42d60bcbbe9682608369d6b27b
