apiVersion: v1
kind: Service
metadata:
  name: wikipedia-server-svc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: wikipedia-server
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
