apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-staging

resources:
  - namespace.yaml
  - ../../base

namePrefix: staging-

images:
  - name: PROJECT/IMAGE
    newName: typescriptlover/the_project
    # Staging automatically uses latest from main branch
