apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummysite-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummysite-controller
  template:
    metadata:
      labels:
        app: dummysite-controller
    spec:
      serviceAccountName: dummysite-controller
      containers:
        - name: controller
          image: typescriptlover/dummysite_controller:9a49e77fa387b905fc09c11450db87f9ee6048c8
          imagePullPolicy: Always
          env:
            - name: NODE_TLS_REJECT_UNAUTHORIZED # needed or auth fail
              value: "0"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
