apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-site-route
  namespace: default
spec:
  parentRefs:
    - name: dummysite-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: example-site-service
          port: 80
