apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crd.yaml
- rbac.yaml
- deployment.yaml
images:
- name: PROJECT/IMAGE
  newName: typescriptlover/dummysite_controller
  newTag: b7300807b71667c3c92e37eb4f659582641de1ed
