apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd.yaml
  - rbac.yaml
  - deployment.yaml
images:
  - name: PROJECT/IMAGE
    newName: typescriptlover/dummysite-controller
    newTag: latest
