apiVersion: v1
kind: ServiceAccount
metadata:
  name: dummysite-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dummysite-controller
  namespace: default
rules:
  - apiGroups: ["stable.dwk"]
    resources: ["dummysites"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps", "services"]
    verbs: ["get", "list", "create", "update", "patch", "delete", "replace"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "patch", "delete", "replace"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dummysite-controller
  namespace: default
subjects:
  - kind: ServiceAccount
    name: dummysite-controller
    namespace: default
roleRef:
  kind: Role
  name: dummysite-controller
  apiGroup: rbac.authorization.k8s.io
