apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wikipedia-site-route
  namespace: default
spec:
  parentRefs:
    - name: dummysite-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /wikipedia
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: wikipedia-site-service
          port: 80
