apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: log-output
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kristianka/DevOpsWithKubernetes
    targetRevision: HEAD
    path: log_output/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: exercises
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
