# log_output/manifests/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  # - persistentvolume.yaml
  # - persistentvolumeclaim.yaml
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- istio-gateway.yaml
- virtualservice.yaml
  # - gateway.yaml
  # - httproute.yaml
images:
- name: PROJECT/IMAGE
  newName: typescriptlover/log_output
  newTag: cad8d36074b29e42d60bcbbe9682608369d6b27b
