apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- persistentvolume.yaml
- persistentvolumeclaim.yaml
- application.yaml
- gateway.yaml
- httproute.yaml
images:
- name: PROJECT/IMAGE
  newName: typescriptlover/log_output
  newTag: 201b8acfdf14702d9ed8e5ea383b2e44f0772953
