# log_output/manifests/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  # - persistentvolume.yaml
  # - persistentvolumeclaim.yaml
  - istio-gateway.yaml
  - virtualservice.yaml
  # - gateway.yaml
  # - httproute.yaml
images:
  - name: PROJECT/IMAGE
    newName: log-output
    newTag: latest
