name: Build and publish ping pong app

on:
    push:
        branches:
            - "**"
        paths:
            - "ping_pong/**"
            - ".github/workflows/ping_pong_build.yaml"

jobs:
    build-publish:
        name: Build, Push, Release ping pong app
        runs-on: ubuntu-latest
        environment: deploy

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            # tag image with the GitHub SHA to get a unique tag
            - name: Build and publish ping pong app
              working-directory: ./ping_pong
              run: |-
                  docker build --tag "${{ secrets.DOCKERHUB_USERNAME }}/ping_pong:$GITHUB_SHA" .
                  docker push "${{ secrets.DOCKERHUB_USERNAME }}/ping_pong:$GITHUB_SHA"

            - name: Set up Kustomize
              uses: imranismail/setup-kustomize@v2

            - name: Use right image
              working-directory: ./ping_pong/manifests
              run: kustomize edit set image PROJECT/IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/ping_pong:$GITHUB_SHA

            - name: commit kustomization.yaml to GitHub
              uses: EndBug/add-and-commit@v9
              with:
                  add: "ping_pong/manifests/kustomization.yaml"
                  message: New version released ${{ github.sha }}
