name: Build and publish the_project app

on:
    push:
        branches:
            - "**"
        paths:
            - "the_project/**"
            - ".github/workflows/the_project_build.yaml"

jobs:
    build-publish:
        name: Build, Push, Release the_project app
        runs-on: ubuntu-latest
        environment: deploy

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            # tag image with the GitHub SHA to get a unique tag
            - name: Build and publish the_project app
              working-directory: ./the_project
              run: |-
                  docker build --tag "${{ secrets.DOCKERHUB_USERNAME }}/the_project:$GITHUB_SHA" .
                  docker push "${{ secrets.DOCKERHUB_USERNAME }}/the_project:$GITHUB_SHA"

            - name: Set up Kustomize
              uses: imranismail/setup-kustomize@v2

            - name: Use right image
              working-directory: ./the_project/manifests
              run: kustomize edit set image PROJECT/IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/the_project:$GITHUB_SHA

            - name: commit kustomization.yaml to GitHub
              uses: EndBug/add-and-commit@v9
              with:
                  add: "the_project/manifests/kustomization.yaml"
                  message: New version released ${{ github.sha }}
                  pull: "--rebase --autostash"
